name: Bug Report
description: Report a bug or unexpected behaviour in the project.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - maythiricho
type: bug

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a bug report!  
        Please provide as much detail as possible so we can reproduce and fix the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
      placeholder: Describe the problem clearly...
    validations:
      required: true

  - type: input
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the bug?
      placeholder: |
        1. Go to...
        2. Click...
        3. Observe...
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of the software are you running?
      options:
        - v0.1.0.2
        - Latest from GitHub
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Include error messages, console output, or screenshots.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
